---
- name: Include versions variables.
  include_vars: "versions.yml"

- name: Define elasticsearch_version.
  set_fact:
    elasticsearch_version: "{{ __elasticsearch_version }}"
  when: elasticsearch_version is not defined

- fail: msg="Unsupported Elasticsearch version {{ elasticsearch_version }}. Acceptable versions are {{ ', '.join(__elasticsearch_acceptable_versions) }}"
  when: elasticsearch_version not in __elasticsearch_acceptable_versions

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Configure Elasticsearch.
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0750
  notify: restart elasticsearch

- name: Start Elasticsearch.
  service: name=elasticsearch state=started enabled=yes

- name: Make sure Elasticsearch is running before proceeding.
  wait_for: port={{ elasticsearch_http_port }} delay=3 timeout=300
