---
- name: Add Elasticsearch repository.
  apt_repository:
    filename: '{{ source_list_file_name }}'
    repo: 'deb https://artifacts.elastic.co/packages/5.x/apt stable main'
    state: present
    update_cache: yes
